version: "3.9"
services:
  env:
    build: .
    # image: yuhengy/shd-formal_verification_rec
    platform: linux/amd64
    volumes:
      - .:/vagrant
    stdin_open: true # docker run -i
    tty: true        # docker run -t

